import { KeyCodeDef } from "./def";

export const numbers = [
  {
    name: "N1",
    char: "1",
    char2: "!",
    description: "1 and ! (EXCLAMATION)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "N2",
    char: "2",
    char2: "@",
    description: "2 and @ (AT SIGN)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "N3",
    char: "3",
    char2: "#",
    description: "3 and # (HASH / POUND)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "N4",
    char: "4",
    char2: "$",
    description: "4 and $ (DOLLAR)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "N5",
    char: "5",
    char2: "%",
    description: "5 and % (PERCENT)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "N6",
    char: "6",
    char2: "^",
    description: "6 and ^ (CARET)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "N7",
    char: "7",
    char2: "&",
    description: "7 and & (AMPERSAND)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "N8",
    char: "8",
    char2: "*",
    description: "8 and * (ASTERISK / STAR)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "N9",
    char: "9",
    char2: "(",
    description: "9 and ( (LEFT PARENTHESIS)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "N0",
    char: "0",
    char2: ")",
    description: "0 and ) (RIGHT PARENTHESIS)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
] as const satisfies readonly KeyCodeDef[];
