import { KeyCodeDef } from "./def";

export const symbols = [
  {
    name: "EXCL",
    char: "!",
    description: "! (EXCLAMATION)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "AT",
    char: "@",
    description: "@ (AT SIGN)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "HASH",
    char: "#",
    description: "# (HASH / POUND)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "DLLR",
    char: "$",
    description: "$ (DOLLAR)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "PRCNT",
    char: "%",
    description: "% (PERCENT)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "CARET",
    char: "^",
    description: "^ (CARET)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "AMPS",
    char: "&",
    description: "& (AMPERSAND)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "STAR",
    char: "*",
    description: "* (ASTERISK / STAR)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "LPAR",
    char: "(",
    description: "( (LEFT PARENTHESIS)",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "RPAR",
    char: ")",
    description: "RIGHT PARENTHESIS",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "EQUAL",
    char: "=",
    char2: "+",
    description: "EQUAL and PLUS",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "PLUS",
    char: "+",
    description: "PLUS",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "MINUS",
    char: "-",
    char2: "_",
    description: "MINUS and UNDERSCORE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "UNDER",
    char: "_",
    description: "UNDERSCORE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "SLASH",
    char: "/",
    char2: "?",
    description: "FORWARD SLASH and QUESTION MARK",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "QMARK",
    char: "?",
    description: "QUESTION MARK",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "BSLH",
    char: "\\",
    char2: "|",
    description: "BACKSLASH and PIPE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "PIPE",
    char: "|",
    description: "PIPE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "NUBS",
    char: "\\",
    char2: "/",
    description: "Non-US BACKSLASH and PIPE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "PIPE2",
    char: "|",
    description: "PIPE 2",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "SEMI",
    char: ";",
    char2: ":",
    description: "SEMICOLON and COLON",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "COLON",
    char: ":",
    description: "COLON",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "SQT",
    char: "'",
    char2: '"',
    description: "SINGLE QUOTE and DOUBLE QUOTE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "DQT",
    char: '"',
    description: "DOUBLE QUOTE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "COMMA",
    char: ",",
    char2: "<",
    description: "COMMA and LESS THAN",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "LT",
    char: "<",
    description: "LESS THAN",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "DOT",
    char: ".",
    char2: ">",
    description: "PERIOD and GREATER THAN",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "GT",
    char: ">",
    description: "GREATER THAN",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "LBKT",
    char: "[",
    char2: "{",
    description: "LEFT BRACKET and LEFT BRACE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "LBRC",
    char: "{",
    description: "LEFT BRACE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "RBKT",
    char: "]",
    char2: "}",
    description: "RIGHT BRACKET and RIGHT BRACE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "RBRC",
    char: "}",
    description: "RIGHT BRACE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "GRAVE",
    char: "`",
    char2: "~",
    description: "GRAVE ACCENT and TILDE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "TILDE",
    char: "~",
    description: "TILDE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "NUHS",
    char: "№",
    char2: "Ë",
    description: "Non-US HASH/POUND and TILDE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
  {
    name: "TILDE2",
    char: "~",
    description: "TILDE",
    os: {
      w: true,
      l: true,
      m: true,
      a: true,
      i: true,
    },
  },
] as const satisfies readonly KeyCodeDef[];
